spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: BookApp.java

book:
  name: bookname
  author: bookauthor
  isbn: ${random.uuid}
  description: ${book.name}, is nice!
